### ISSUE TITLE
Use Ubuntu 18.04 to build binaries

### ISSUE THREAD

**Issue by reznikmm** [alire-project/GNAT-FSF-builds#19]
Hello!

I've tried these binaries and them fail on Ubuntu 18.04:
```
gprbuild: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by gprbuild)
```

I would like them to run on Ubuntu 18.04, so I will be able to build my projects for Ubuntu 18.04. The older the better, but Ubuntu 16.04 is declared obsolescenced for Github Actions.

**Comment by reznikmm** [comment]
Also `macos-latest` will [be switched](https://github.com/actions/virtual-environments/issues/4060) to macos 11 shortly, so bineries could stop working on macos 10 in the same way.

**Comment by reznikmm** [comment]
This could be related to [#792](https://github.com/alire-project/alire/issues/792) in part of statically linking.

**Comment by Fabien-Chouteau** [comment]
Done
