### ISSUE TITLE
Problem getting this set up on NixOS

### ISSUE THREAD

**Issue by ethindp** [alire-project/GNAT-FSF-builds#35]
So I'm trying to fix the "gnat problem" in NixOS, where gnat can't be built because it recursively tries to build consecutively older versions of gnat before reaching an end version of 4.1.0. I've got gnat working, sort-of, but when I tried to get gprbuild working (after changing the gprbuild-boot package to use the binaries in this repository so it could build itself), I'm getting this error:

       > Build Libraries
       >    [gprlib]       xmlada_unicode.lexch
       >    [gprlib]       xmlada_input_sources.lexch
       >    [link library] libxmlada_unicode.so
       > /nix/store/g800rmd1q6bi3qdliwsanyiych11qqwp-gnat-x86_64-11.2.0-4/bin/../lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find crti.o: No such file or directory
       > collect2: error: ld returned 1 exit status
       > gprlib: /nix/store/g800rmd1q6bi3qdliwsanyiych11qqwp-gnat-x86_64-11.2.0-4/bin/gcc execution error
       > gprbuild: could not build library for project xmlada_unicode
       > make: *** [Makefile:63: relocatable] Error 4

When gprbuild is built, [this patch](https://aur.archlinux.org/cgit/aur.git/plain/relocatable-build.patch?h=gprbuild&id=1d4e8a5cb982e79135a0aaa3ef87654bed1fe4f0) is applied, which prevents gprbuild from being linked statically. The only reason I'm doing all this via nixpkgs is because the provided toolchains here do not work out of the box (they assume that the interpreter is in its usual location), so I have to patch their interpreters and shebangs and stuff for them to work properly. Do I have to do something special for crti.o to be found? I'm not cross-compiling, so I'm confused why ld needs this.

**Comment by Fabien-Chouteau** [comment]
Hi @ethindp, I,m sorry I didn't react here. Did you find a solution?
