### ISSUE TITLE
`ar.exe` tries to load libdep.a (from lib\bfd-plugins) as a DLL and fails

### ISSUE THREAD

**Issue by damaki** [alire-project/GNAT-FSF-builds#36]
I've encountered a regression for #25 on gnat_native_11.2.4 and gnat_native_12.1.1 where `ar.exe` tries to load `libdep.a` and fails, resulting in the following error dialog which appears several times:

![image](https://user-images.githubusercontent.com/720413/174869917-346ab7df-e6d4-46e2-982c-3d30e037ecd8.png)

When I click on the OK button my library is still built successfully.

I can work around this issue by deleting `libdep.a`.

**Comment by Fabien-Chouteau** [comment]
Fixed for GNAT FSF 12
