### ISSUE TITLE
No line numbers in tracebacks with 11.2

### ISSUE THREAD

**Issue by mosteo** [alire-project/GNAT-FSF-builds#37]
On Ubuntu 20.04, using the latest GNAT in Alire (11.2.4) I get this kind of tracebacks:

```
0xdf7f15 alire__raise_checked_error at ???
0xa91661 alire__os_lib__subprocess__checked_spawn at ???
0xb7c310 alire__publish__check_build at ???
0xb884ee alire__publish__run_steps at ???
0xb8de32 alire__publish__remote_origin at ???
0xb8b45e alire__publish__local_repository at ???
0x4c76f3 alr__commands__publish__execute at ???
0x540fce alr__commands__sub_cmd__execute at ???
0x54cb2c alr__commands__execute at ???
0x43efce _ada_alr__main at ???
0x44190f main at ???
[/lib/x86_64-linux-gnu/libc.so.6]
0x7f3aeef2a081
[/home/jano/opt/bin/alr]
0x43eeac _start at ???
0xfffffffffffffffe
```

Using CE 2021 I get the expected line numbers.

This is building Alire with its regular project files, so the same switches are being used (from [alire_common.gpr](https://github.com/alire-project/alire/blob/master/alire_common.gpr))

**Comment by Fabien-Chouteau** [comment]
I don't know why, -Es binder switch should be enough.

**Comment by mosteo** [comment]
What I find even more curious is that file names do appear. Past similar problems usually were all or nothing.

**Comment by Fabien-Chouteau** [comment]
@mosteo Known problem for GNAT FSF 11, it is fixed in GNAT FSF 12.
