### ISSUE TITLE
gdb depends on libpython3.8

### ISSUE THREAD

**Issue by JeremyGrosser** [alire-project/GNAT-FSF-builds#51]
After switching to the gnat-fsf-13.1.0 toolchain, arm-eabi-gdb stops working on Debian bookworm, because `libpython3.8.so.1.0` is unavailable. Python 3.11 is the release included with Debian stable.

```
synack@polar ~/src/rp2040_hal/tests(master) $ eval $(alr printenv)
synack@polar ~/src/rp2040_hal/tests(master) $ arm-eabi-gdb
arm-eabi-gdb: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by JeremyGrosser** [comment]
I've confirmed that adding `--without-python` to the gdb configure flags removes the dependency on libpython3.8. I was unable to find an option for static linking.
https://github.com/alire-project/GNAT-FSF-builds/compare/main...JeremyGrosser:GNAT-FSF-builds:gdb-without-python

**Comment by Fabien-Chouteau** [comment]
Thanks for the report @JeremyGrosser.

I don't think I want to disable python for the builds as it brings many useful features. Maybe there's a way to disable it at run-time?

**Comment by reznikmm** [comment]
# Workaround :wrench: 

To make `gdb` from `gnat_native_13.2.0_788a01f9` work I've rebuilt libpython3.8 for my Ubuntu 22.04. This is rather simple (I used a docker to have a clean build env).
* Download sources from [Ubuntu](https://packages.ubuntu.com/focal/libpython3.8) and my patch
* Run
```
tar xaf python3.8_3.8.10.orig.tar.xz 
cd Python-3.8.10
tar xaf ../python3.8_3.8.10-0ubuntu1~20.04.8.debian.tar.xz
patch -p1 < ../python-3.8.patch
sudo apt install build-essential
sudo apt-get build-dep .
sudo ln -s /usr/lib/x86_64-linux-gnu/libmpdec.so.2.5.1 /usr/lib/x86_64-linux-gnu/libmpdec.so.2
dpkg-buildpackage -b
```
* Now you have needed packages, install them
```
apt install ./libpython3.8_3.8.10-0ubuntu1~20.04.8_amd64.deb ./libpython3.8-stdlib_3.8.10-0ubuntu1~20.04.8_amd64.deb ./libpython3.8-minimal_3.8.10-0ubuntu1~20.04.8_amd64.deb
```

**Comment by reznikmm** [comment]
[python-3.8.patch](https://github.com/alire-project/GNAT-FSF-builds/files/13470978/python-3.8.patch.zip)

**Comment by yrashk** [comment]
I want to add a suggestion here. It's possible to use [`RPATH`](https://en.wikipedia.org/wiki/Rpath) with (`$ORIGIN` on Linux and  `@loader_path` on macOS) to ship a shared library side-by-side.

**Comment by Fabien-Chouteau** [comment]
Hello here, so I decided to disable python support in the next builds (14.1.3). I don't see a good way to provide python and it was never enabled for our Windows builds anyway.

The workaround, if Python support is really important for you, will be to use the distrib GDB
